---
title: "ENVS 193DS Final"
author: "Angela Larson"
date: "8 June 2025"
format:
  html:
    toc: true # use this to display a table of contents
execute:
  message: false # use this to make sure messages don't show up
  warning: false # use this to make sure warnings don't show up
---

[Repo Link]: https://github.com/angelalarson/ENVS-193DS_spring-2025_final.git

```{r to read in packages and data}

```

# Problem 1

## a. Transparent statistical methods

In part one, they used a pearson correlation test. In part two, they used a one-way ANOVA.

## b. More Information Needed

Since the ANOVA returned at least two or more of the variables are statistically different from each other, we need to run a Tukey's post-hoc test to determine which specific nitrogen-containing variables are statistically different from each other. The ANOVA told us a statistically significant difference exists within the variables (urban land, atmospheric deposition, fertilizer, wastewater treatment, and grasslands), the post-hoc identifies between which variables.

Furthermore, we would run an eta squared test (n^2^) to determine the effect size. The effect size determines how much the grouping variable (urban land, atmospheric deposition, fertilizer, wastewater treatment, and grasslands) explains the response variable (average nitrogen load), given by the size of the variation in the response variable as described by the grouping variable. To put it simply, it describes how big of a difference exists between the variables, not just the significance. 

## c. Suggestions for re-writing

We determined there was a correlation between distance from headwater (km) and annual total nitrogen load (kg year{-1}) (Pearson correlation test, r = **correlation coefficient**, p = 0.03, $\alpha$ = **significance level**). 

We found a small/medium/large ($\eta^2$ = **n^2^**) difference between sources (urban land, atmospheric deposition, fertilizer, wastewater treatment, and grasslands) in average nitrogen load (kg year{-1}), (one-way ANOVA, F(**among groups df, within groups df**) = **F-statistic**, p = 0.02, $\alpha$ = **significance level**). On average, **source** tended to have smaller/larger nitrogen loads than **source** (Tukey's HSD: p < **p-value**).

# Problem 4

## a. Comparing Visualizations

I decided to represent the data in Homework 2 as a line graph and box plots, and didn't really get any clear visuals of the data at the time. By grouping the data into four different time slots and representing them as bar graphs, I was able to see visual patterns appear between step count and time on campus.

There aren't many similarities, however I similarly saw that grouping steps by exercise type really showed no correlation between average step count and exercise type. 

The most clear pattern is in the affective visualization as the average number of steps is somewhat correlated to time on campus; however, all the standard error bars overlap with each other so that correlation is only observed and would not be supported statistically. I plotted number of steps against time on campus as a line graph in homework 2, which showed a similar correlation as to what was observed in the final visualization. However, with so few points in homework 2, it is hard to compare as the data was quite variable at the time.

I received primarily positive feedback, however it was suggested that I incorporate color into my drawing to visually distinguish between mean and error bars and buildings. I incorporated color to make it as visually distinguishable as possible.

## b. Sharing your affective visualization

This was done during section on Friday.
